server:
  port: 8083

spring:
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
  flyway:
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380
      password: 123