server:
  port: 8084

spring:
  datasource:
    password: 
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
  flyway:
    url: jdbc:postgresql://localhost:5434/postgres
    user: postgres
    password: 
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6381
      password: 