version: '3.8'

services:
  # User service
  
  user-service-cache:
    container_name: 'user-service-cache'
    image: redis:7
    restart: on-failure
    command: bash -c "redis-server --appendonly yes --requirepass 123"
    ports:
      - '6379:6379'
    networks:
      backend:
        aliases:
          - "user-cache"
  user-service-database:
    image: 'postgres:15.0'
    container_name: 'user-service-database'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "user-database"
  user-service-backend:
    container_name: 'user-service-backend'
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-user-service
    ports:
      - '8081:8081'
    networks:
      - backend
    depends_on:
      config-server:
        condition: service_started
      user-service-database:
        condition: service_healthy
      user-service-cache:
        condition: service_started
  # Config server
  config-server:
    container_name: 'config-server'
    ports:
      - '8082:8082'
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-config-server
    networks:
      backend:
        aliases:
          - "configserver"

#Product service

  product-service-cache:
    container_name: 'product-service-cache'
    image: redis:7
    restart: on-failure
    command: bash -c "redis-server --appendonly yes --requirepass 123"
    ports:
      - '6380:6379'
    networks:
      backend:
        aliases:
          - "product-cache"
  product-service-database:
    image: 'postgres:15.0'
    container_name: 'product-service-database'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "productdb"
  product-service-backend:
    container_name: 'product-service-backend'
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-product-service
    ports:
      - '8083:8083'
    networks:
      - backend
    depends_on:
      config-server:
        condition: service_started
      product-service-database:
        condition: service_healthy
      product-service-cache:
        condition: service_started

  
networks:
  backend:
    driver: bridge
  