version: '3.8'

services:
  # User service
  
  user-service-cache:
    container_name: 'user-service-cache'
    image: redis:7
    restart: on-failure
    command: bash -c "redis-server --appendonly yes --requirepass 123"
    ports:
      - '6379:6379'
  user-service-database:
    image: 'postgres:15.0'
    container_name: 'user-service-database'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  user-service-backend:
    container_name: 'user-service-backend'
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-user-service
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-database/postgres"
      - "SPRING_FLYWAY_URL=jdbc:postgresql://user-service-database/postgres"
    ports:
      - '8081:8081'
    depends_on:
      user-service-database:
        condition: service_healthy
      user-service-cache:
        condition: service_started
        
        