server:
  port: 8081

spring:
  application:
    name: user-microservice
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32771/postgres
  flyway:
    url: jdbc:postgresql://localhost:32771/postgres
    user: postgres
    password: postgres