server:
  port: 8081

spring:
  datasource:
    password: 
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 