FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR app

COPY ../pom.xml pom.xml
COPY ../user-microservice/src user-microservice/src
COPY ../user-microservice/pom.xml user-microservice/pom.xml

RUN mvn clean package -f user-microservice/pom.xml &&  \
    java -Djarmode=layertools -jar user-microservice/target/user-microservice-0.0.1-SNAPSHOT.jar extract --destination extracted

FROM eclipse-temurin:17-jre
ARG JAR_FILE=user-microservice-0.0.1-SNAPSHOT.jar
WORKDIR app

COPY --from=build app/extracted/dependencies/ ./
COPY --from=build app/extracted/spring-boot-loader/ ./
COPY --from=build app/extracted/snapshot-dependencies/ ./
COPY --from=build app/extracted/application/ ./

ENTRYPOINT exec java org.springframework.boot.loader.launch.JarLauncher ${0} ${@}