FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR app

COPY ../pom.xml pom.xml
COPY ../order-microservice/src order-microservice/src
COPY ../order-microservice/pom.xml order-microservice/pom.xml

RUN mvn clean package -f order-microservice/pom.xml &&  \
    java -Djarmode=layertools -jar order-microservice/target/order-microservice-0.0.1-SNAPSHOT.jar extract --destination extracted

FROM eclipse-temurin:17-jre
ARG JAR_FILE=order-microservice-0.0.1-SNAPSHOT.jar
WORKDIR app

COPY --from=build app/extracted/dependencies/ ./
COPY --from=build app/extracted/spring-boot-loader/ ./
COPY --from=build app/extracted/snapshot-dependencies/ ./
COPY --from=build app/extracted/application/ ./

ENTRYPOINT exec java org.springframework.boot.loader.launch.JarLauncher ${0} ${@}