FROM maven:3.9.0-eclipse-temurin-17 AS build
WORKDIR app

COPY ../pom.xml pom.xml
COPY ../config-server/src config-server/src
COPY ../config-server/pom.xml config-server/pom.xml

RUN mvn clean package -f config-server/pom.xml &&  \
    java -Djarmode=layertools -jar config-server/target/config-server-0.0.1-SNAPSHOT.jar extract --destination extracted

FROM eclipse-temurin:17-jre
ARG JAR_FILE=config-server-0.0.1-SNAPSHOT.jar
WORKDIR app

COPY --from=build app/extracted/dependencies/ ./
COPY --from=build app/extracted/spring-boot-loader/ ./
COPY --from=build app/extracted/snapshot-dependencies/ ./
COPY --from=build app/extracted/application/ ./

ENTRYPOINT exec java org.springframework.boot.loader.launch.JarLauncher ${0} ${@}