version: '3.8'

services:
  eshop-user-db:
    image: 'postgres:15.0'
    container_name: 'eshop-user-db'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  eshop-user-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      eshop-user-db:
        condition: service_healthy