version: '3.8'

services:
  database:
    image: 'postgres:15.0'
    container_name: 'user-service-database'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
    ports:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - '8081:8081'
    depends_on:
      database:
        condition: service_healthy